/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_STORAGE_FILES           8
#define MMAP_STORAGE_CHECKSUM        0xA8CF

enum MMAP_STORAGE_LISTS {
    MMAP_STORAGE_ASKING_BIN = 0,        /*!< asking.bin */
    MMAP_STORAGE_DONE_BIN = 1,        /*!< done.bin */
    MMAP_STORAGE_ERROR_BIN = 2,        /*!< error.bin */
    MMAP_STORAGE_IDLE_BIN = 3,        /*!< idle.bin */
    MMAP_STORAGE_OFFLINE_BIN = 4,        /*!< offline.bin */
    MMAP_STORAGE_TOOL_BIN = 5,        /*!< tool.bin */
    MMAP_STORAGE_WAITING_BIN = 6,        /*!< waiting.bin */
    MMAP_STORAGE_WORKING_BIN = 7,        /*!< working.bin */
};
